apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: vscn
  name: vscn-loader
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: database-accessor-ksa
          restartPolicy: Never
          containers:
            - name: vscn-loader
              image: gcr.io/leafy-beach-375514/vscn-loader:1.0.0_linux_amd64
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: "500m"
                  memory: "1024M"
                requests:
                  cpu: "500m"
                  memory: "1024M"
              env:
                - name: YEARS
                  value: "2023,2022,2021,2020,2019"
                - name: POSTGRES_HOST
                  value: "localhost"
                - name: POSTGRES_PORT
                  value: "5432"
                - name: POSTGRES_DATABASE
                  value: "vscn"
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: vscn-database-secrets-k
                      key: POSTGRES_PASSWORD
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: vscn-database-secrets-k
                      key: POSTGRES_USER
            - name: cloud-sql-proxy
              image: gcr.io/cloudsql-docker/gce-proxy:latest
              resources:
                limits:
                  cpu: "100m"
                  memory: "128M"
                requests:
                  cpu: "100m"
                  memory: "128M"
              command:
                - "/cloud_sql_proxy"
                - "-instances=leafy-beach-375514:europe-west3:vscn-database=tcp:5432"
              securityContext:
                runAsNonRoot: true