
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscn-server-deployment
  namespace: vscn
  labels:
    app: vscn-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vscn-server
  template:
    metadata:
      labels:
        app: vscn-server
    spec:
      serviceAccountName: database-accessor-ksa
      containers:
        - name: vscn-server
          image: gcr.io/leafy-beach-375514/vscn-server:1.0.0_linux_amd64
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "100m"
              memory: "256M"
            requests:
              cpu: "100m"
              memory: "256M"
          env:
            - name: POSTGRES_HOST
              value: "localhost"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DATABASE
              value: "vscn"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vscn-database-secrets-k
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: vscn-database-secrets-k
                  key: POSTGRES_USER
          ports:
            - containerPort: 80
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          resources:
            limits:
              cpu: "100m"
              memory: "128M"
            requests:
              cpu: "100m"
              memory: "128M"
          command:
            - "/cloud_sql_proxy"
            - "-instances=leafy-beach-375514:europe-west3:vscn-database=tcp:5432"
          securityContext:
            runAsNonRoot: true
