VERSION 0.6
FROM python:3.10
WORKDIR /vscn-loader

build:
    COPY vscn_loader/ vscn_loader/
    COPY scripts/ scripts/
    COPY requirements.txt requirements.txt
    RUN apt-get update && apt-get -y install jq
    RUN chmod +x scripts/extract-cve.sh
    RUN chmod +x scripts/extract-matchers.sh
    ENV PYTHONPATH="/vscn-loader"
    RUN pip install -r requirements.txt
    SAVE ARTIFACT /vscn-loader /vscn-loader
    ENTRYPOINT ["python", "vscn_loader/main.py"]
    SAVE IMAGE vscn-loader:latest


