VERSION 0.6

deployment:
    FROM --platform=linux/amd64 python:3.10
    WORKDIR /vscn-loader

    COPY vscn_loader/ vscn_loader/
    COPY scripts/ scripts/
    COPY requirements.txt requirements.txt
    RUN apt-get update && apt-get -y install jq
    RUN chmod +x scripts/extract-cve.sh
    RUN chmod +x scripts/extract-matchers.sh
    ENV PYTHONPATH="/vscn-loader"
    RUN pip install -r requirements.txt
    SAVE ARTIFACT /vscn-loader /vscn-loader
    ENTRYPOINT ["python", "vscn_loader/main.py"] 
    SAVE IMAGE vscn-loader:1.0.0
    SAVE IMAGE --push eu.gcr.io/leafy-beach-375514/vscn-loader:1.0.0-amd64



local:
    FROM python:3.10
    WORKDIR /vscn-loader

    COPY vscn_loader/ vscn_loader/
    COPY scripts/ scripts/
    COPY requirements.txt requirements.txt
    RUN apt-get update && apt-get -y install jq
    RUN chmod +x scripts/extract-cve.sh
    RUN chmod +x scripts/extract-matchers.sh
    ENV PYTHONPATH="/vscn-loader"
    RUN pip install -r requirements.txt
    SAVE ARTIFACT /vscn-loader /vscn-loader
    ENTRYPOINT ["python", "vscn_loader/main.py"]
    
    SAVE IMAGE vscn-loader:1.0.0




deployment:
    FROM --platform=linux/amd64 python:3.10
    WORKDIR /vscn-server
    COPY vscn_server/ vscn_server/
    COPY requirements.txt requirements.txt
    RUN pip install -r requirements.txt
    ENV PYTHONPATH="/vscn-server"
    CMD ["gunicorn", "-w", "4", "vscn_server.app:app", "-b", "0.0.0.0:80"]
    SAVE IMAGE --push eu.gcr.io/leafy-beach-375514/vscn-server:1.0.0-amd64

local:
    FROM python:3.10
    WORKDIR /vscn-server
    COPY vscn_server/ vscn_server/
    COPY requirements.txt requirements.txt
    RUN pip install -r requirements.txt
    ENV PYTHONPATH="/vscn-server"
    CMD ["gunicorn", "-w", "4", "vscn_server.app:app", "-b", "0.0.0.0:80"]
    SAVE IMAGE vscn-server:1.0.0