apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-accessor-ksa
  namespace: vscn
  annotations:
    iam.gke.io/gcp-service-account: vscn-secret-accessor-iam@leafy-beach-375514.iam.gserviceaccount.com


# leafy-beach-375514.svc.id.goog

# gcloud iam service-accounts create vscn-secret-accessor-iam --project=leafy-beach-375514


# gcloud projects add-iam-policy-binding leafy-beach-375514 \
#     --member "serviceAccount:vscn-secret-accessor-iam@leafy-beach-375514.iam.gserviceaccount.com" \
#     --role "roles/secretmanager.secretAccessor"


# gcloud iam service-accounts add-iam-policy-binding vscn-secret-accessor-iam@leafy-beach-375514.iam.gserviceaccount.com \
#     --role roles/iam.workloadIdentityUser \
#     --member "serviceAccount:leafy-beach-375514.svc.id.goog[vscn/secret-accessor-ksa]"
#     --project=leafy-beach-375514



#   kubectl annotate serviceaccount secret-accessor-ksa \
#     --namespace vscn \
#     iam.gke.io/gcp-service-account=vscn-secret-accessor-iam@leafy-beach-375514.iam.gserviceaccount.com