apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vscn-server-es
  namespace: vscn
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: vscn-database-secrets-k
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: vscn-database-secrets