insert into product_mappings (product_name, cve_product_name)
values 
	('android-json', 'android'),
	('bcpkix-jdk15on', 'legion-of-the-bouncy-castle-java-crytography-api'),
	('bcpkix-jdk15on', 'the_bouncy_castle_crypto_package_for_java'),
	('hibernate-core', 'hibernate_orm'),
	('jackson-annotations', 'jackson-databind'),
	('json-smart', 'json-smart-v2'),
	('junit-jupiter', 'junit'),
	('junit-jupiter-api', 'junit'),
	('junit-jupiter-engine', 'junit'),
	('junit-jupiter-params', 'junit'),
	('junit-platform-commons', 'junit'),
	('junit-platform-engine', 'junit'),
	('junit-vintage-engine', 'junit'),
	('keycloak-adapter-core', 'keycloak'),
	('keycloak-authz-client', 'keycloak'),
	('keycloak-common', 'keycloak'),
	('keycloak-core', 'keycloak'),
	('keycloak-spring-boot-adapter-core', 'keycloak'),
	('keycloak-spring-boot-starter', 'keycloak'),
	('keycloak-spring-security-adapter', 'keycloak'),
	('log4j-api', 'log4j'),
	('log4j-to-slf4j', 'log4j'),
	('logback-classic', 'logback'),
	('logback-core', 'logback'),
	('netty-buffer', 'netty'),
	('netty-codec', 'netty'),
	('netty-codec-http', 'netty'),
	('netty-codec-http2', 'netty'),
	('netty-codec-socks', 'netty'),
	('netty-common', 'netty'),
	('netty-handler', 'netty'),
	('netty-handler-proxy', 'netty'),
	('netty-transport', 'netty'),
	('netty-transport-native-epoll', 'netty'),
	('netty-transport-native-unix-common', 'netty'),
	('reactor-netty', 'reactor_netty'),
	('spring-boot', 'spring_boot'),
	('spring-boot-starter-reactor-netty','reactor_netty'),
	('spring-boot-starter-tomcat', 'tomcat'),
	('spring-security-config', 'spring_security'),
	('spring-security-core', 'spring_security_core'),
	('tomcat-embed-core', 'tomcat'),
	('tomcat-embed-websocket', 'tomcat'),
	('spring-web', 'spring_web_services')

;