insert into dependency_product_mappings (dependency_name, product_name, language)
values 
	('bcpkix-jdk15on', 'legion-of-the-bouncy-castle-java-crytography-api', 'java'),
	('bcpkix-jdk15on', 'the_bouncy_castle_crypto_package_for_java', 'java'),
	('hibernate-core', 'hibernate_orm', 'java'),
	('jackson-annotations', 'jackson-databind', 'java'),
	('json-smart', 'json-smart-v2', 'java'),
	('junit-jupiter', 'junit', 'java'),
	('junit-jupiter-api', 'junit', 'java'),
	('junit-jupiter-engine', 'junit', 'java'),
	('junit-jupiter-params', 'junit', 'java'),
	('junit-platform-commons', 'junit', 'java'),
	('junit-platform-engine', 'junit', 'java'),
	('junit-vintage-engine', 'junit', 'java'),
	('keycloak-core', 'keycloak', 'java'),
	('logback-core', 'logback', 'java'),
	('liquibase-core', 'liquibase', 'java'),
	('netty-transport', 'netty', 'java'),
	('reactor-netty', 'reactor_netty', 'java'),
	('spring-boot', 'spring_boot', 'java'),
	('spring-security-core', 'spring_security', 'java'),
	('spring-security-core', 'spring_security_core', 'java'),
	('tomcat-embed-core', 'tomcat', 'java'),
	('spring-web', 'spring_web_services', 'java'),
	('spring-core', 'spring_framework', 'java'),
	('postgresql', 'postgresql_jdbc_driver', 'java')
;