insert into product_mappings (product_name, cve_product_name)
values 
	('bcpkix-jdk15on', 'legion-of-the-bouncy-castle-java-crytography-api'),
	('bcpkix-jdk15on', 'the_bouncy_castle_crypto_package_for_java'),
	('hibernate-core', 'hibernate_orm'),
	('jackson-annotations', 'jackson-databind'),
	('json-smart', 'json-smart-v2'),
	('junit-jupiter', 'junit'),
	('junit-jupiter-api', 'junit'),
	('junit-jupiter-engine', 'junit'),
	('junit-jupiter-params', 'junit'),
	('junit-platform-commons', 'junit'),
	('junit-platform-engine', 'junit'),
	('junit-vintage-engine', 'junit'),
	('keycloak-core', 'keycloak'),
	('logback-core', 'logback'),
	('liquibase-core', 'liquibase'),
	('netty-transport', 'netty'),
	('reactor-netty', 'reactor_netty'),
	('spring-boot', 'spring_boot'),
	('spring-security-core', 'spring_security'),
	('spring-security-core', 'spring_security_core'),
	('tomcat-embed-core', 'tomcat'),
	('spring-web', 'spring_web_services'),
	('spring-core', 'spring_framework'),
	('postgresql', 'postgresql_jdbc_driver')
;