## Create IAM service account for database
# gcloud iam service-accounts create vscn-database-accessor-iam \
#   --display-name="VSCN Database Accessor" \
#   --project=leafy-beach-375514


## Add roles to the IAM Account
#   gcloud projects add-iam-policy-binding leafy-beach-375514 \
#   --member="serviceAccount:vscn-database-accessor-iam@leafy-beach-375514.iam.gserviceaccount.com" \
#   --role="roles/cloudsql.client" \
#   --project=leafy-beach-375514

#   gcloud projects add-iam-policy-binding leafy-beach-375514 \
#   --member="serviceAccount:vscn-database-accessor-iam@leafy-beach-375514.iam.gserviceaccount.com" \
#   --role="roles/logging.logWriter" \
#   --project=leafy-beach-375514

## Bind IAM with Workload Identity and K8s service account
# gcloud iam service-accounts add-iam-policy-binding \
#   --role="roles/iam.workloadIdentityUser" \
#   --member="serviceAccount:leafy-beach-375514.svc.id.goog[vscn/database-accessor-ksa]" \
#   vscn-database-accessor-iam@leafy-beach-375514.iam.gserviceaccount.com \
#   --project=leafy-beach-375514

## Bind K8s service account with IAM service account
# kubectl annotate serviceaccount \
#   database-accessor-ksa  \
#   iam.gke.io/gcp-service-account=vscn-database-accessor-iam@leafy-beach-375514.iam.gserviceaccount.com

apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-accessor-ksa
  namespace: vscn
  annotations:
    iam.gke.io/gcp-service-account: vscn-database-accessor-iam@leafy-beach-375514.iam.gserviceaccount.com
